### ISSUE TITLE
`/models/<model>/entities/<entity>/attributes/<attr>/mappings`: CRDC-H mappings not found

### ISSUE THREAD

**Issue by joeflack4** [cancerDHC/ccdh-terminology-service#129]
## Description
https://terminology.ccdh.io/models/CRDC-H/entities/BodySite/attributes/site/mappings yields `"mappings":[]`

I know that the mappings are there, because they're in the CCDH Model:
```yml
BodySite:
    name: BodySite
    description: A site in the body of an organism, typically described in terms of
      an anatomical location and optional qualifiers (e.g. left/right, upper/lower).
      But body sites as defined here may include 'non-anatomic' sites, such as the
      location of an implanted medical device.
    notes:
    - Derived from [BodySite in sheet BodySite](https://docs.google.com/spreadsheets/d/1oWS7cao-fgz2MKWtyr8h2dEL9unX__0bJrWKv6mQmM4/edit#gid=1097478901)
    is_a: Entity
    attributes:
      site:
        name: site
        exact_mappings:  # <----------------------------------
        - GDC:Sample.biospecimen_anatomic_site
        - PDC:Sample.biospecimen_anatomic_site
        - ICDC:Sample.sample_site
        - HTAN:Biospecimen.SiteofResectionorBiopsy
        - GDC:Case.primary_site
        - PDC:Case.primary_site
        - GDC:Project.primary_site
        - GDC:Treatment.treatment_anatomic_site
        - PDC:Treatment.treatment_anatomic_site
        - GDC:Diagnosis.site_of_resection_or_biopsy
        - PDC:Diagnosis.site_of_resection_or_biopsy
        description: A term describing any site in the body.
        notes:
        - 'Cardinality: 1..1'
        examples:
        - value: Adenoid
        - value: Adipose
        - value: Adrenal
        values_from: crdch:enum_CRDCH_BodySite_site
        domain: BodySite
        range: CodeableConcept
        multivalued: false
        required: true
```

## Additional information
There are some CRDC-H fields which are showing mappings. For example:

https://terminology.ccdh.io/models/CRDC-H/entities/Specimen/attributes/source_material_type/mappings

```yml
source_material_type:
        name: source_material_type
        exact_mappings:
        - GDC:Sample.sample_type
        - GDC:Sample.sample_type_id
        - PDC:Sample.sample_type
        - PDC:Sample.sample_type_id
        - ICDC:Sample.physical_sample_type
        - HTAN:Biospecimen.BiospecimenType
        description: The general kind of material from which the specimen was derived.
        notes:
        - 'Cardinality: 0..1'
        comments:
        - Values captured here may describe the type of molecular mixture, cell, tissue,
          organ, body fluid, embryo, excretory substance, or experimental system from
          which a specimen was derived.
        examples:
        - value: Tissue
        - value: Blood
        - value: Tumor Aspirate
        - value: Cell Line
        - value: Expanded Next Generation Cancer Model
        - value: Pleural Effusion
        - value: Xenograft Tissue
        values_from: crdch:enum_CRDCH_Specimen_source_material_type
        domain: Specimen
        range: CodeableConcept
        multivalued: false
        required: false
```

Why does mapping info show up for `CRDC-H.Specimen.source_material_type` but not `CRDC-H.BodySite.site`?
