### ISSUE TITLE
/enumerations endpoint(s): return value format changes

### ISSUE THREAD

**Issue by joeflack4** [cancerDHC/ccdh-terminology-service#79]
## Description
Example query: `CRDC-H.Specimen.general_tissue_morphology`

What we're currently returning:
```yml
name: CRDC-H.Specimen.general_tissue_morphology
description: Autogenerated Enumeration for CRDC-H Specimen general_tissue_morphology
permissible_values:
- text: C119010
  description: Peritumoral
  meaning: NCIT:C119010
...
```

What we're thinking about returning:
```yml
name: CRDC-H.Specimen.general_tissue_morphology
description: Autogenerated Enumeration for CRDC-H Specimen general_tissue_morphology
permissible_values:
  - text: Peritumoral
    meaning: NCIT:C119010
...
```

_Edit: 2021/11/01_
@wdduncan Basically we're changing the 'description' field ot say 'text' instead, and we're dropping the field that shows the plain code.

**Comment by gaurav** [comment]
Is this part of the Pilot?

**Comment by joeflack4** [comment]
@gaurav I think we want to change how this is returned from the endpoint as well. But for the purposes of the pilot, I did send a message to matt and brian w/ some transformations I did:

```yml
name: CRDC-H.Specimen.general_tissue_morphology
description: Autogenerated Enumeration for CRDC-H Specimen general_tissue_morphology
permissible_values:
  - text: Not Allowed To Collect
    meaning: NCIT:C141478
  - text: Peritumoral
    meaning: NCIT:C119010
  - text: Abnormal
    meaning: NCIT:C25401
  - text: Normal
    meaning: NCIT:C14165
  - text: Tumor Tissue
    meaning: NCIT:C18009
  - text: Not Reported
    meaning: NCIT:C43234
  - text: Unknown
    meaning: NCIT:C17998
```
