### ISSUE TITLE
Update mappings for: CRDC-H.Specimen.general_tissue_morphology

### ISSUE THREAD

**Issue by joeflack4** [cancerDHC/ccdh-terminology-service#80]
## Description
Currently, an `/enumerations` query returns the following for `CRDC-H.Specimen.general_tissue_morphology`:

```yml
name: CRDC-H.Specimen.general_tissue_morphology
description: Autogenerated Enumeration for CRDC-H Specimen general_tissue_morphology
permissible_values:
- text: Not Allowed To Collect
- text: C119010
  description: Peritumoral
  meaning: NCIT:C119010
- text: C25401
  description: Abnormal
  meaning: NCIT:C25401
- text: C14165
  description: Normal
  meaning: NCIT:C14165
- text: C18009
  description: Tumor Tissue
  meaning: NCIT:C18009
- text: C43234
  description: Not Reported
  meaning: NCIT:C43234
- text: C17998
  description: Unknown
  meaning: NCIT:C17998
```

For value `Not Allowed To Collect`, we need to add the following code: `NCIT:C141478`
